[project]
name = "streaming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "luchzin", email = "luch34976@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi-mail>=1.6.8",
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.5.5",
    "jinja2>=3.1.6",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
streaming = "streaming:main"
[tool.fastapi]
entrypoint = "src.main:app"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
