export const SUPPORTED_LANGUAGES = [
  "🇰🇭 Khmer",
  "🇪🇸 Spanish",
  "🇫🇷 French",
  "🇨🇳 Chinese",
  "🇯🇵 Japanese",
  "🇰🇷 Korean",
  "🇷🇺 Russian",
  "🇩🇪 German",
  "🇮🇹 Italian",
  "🇻🇳 Vietnamese",
  "🇹🇭 Thai",
  "🇮🇩 Indonesian",
  "🇵🇹 Portuguese",
  "🇳🇱 Dutch",
  "🇮🇳 Hindi",
  "🇸🇦 Arabic",
  "🇹🇷 Turkish",
  "🇵🇱 Polish",
  "🇺🇦 Ukrainian",
  "🇬🇧 English",
];